services:
  frontend:
    image: bloglist-frontend
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    container_name: bloglist-front

  backend:
    image: bloglist-backend
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    container_name: bloglist-back
  
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    container_name: reverse-proxy-bloglist
